### ISSUE TITLE
Tree shaking issue

### ISSUE THREAD

**Issue by nickdoherty** [ensdomains/ens-avatar#41]
Hey team,

We currently use this plugin and for a few weeks now we have been experiencing the following issue.

```

✘ [ERROR] Could not resolve "../_virtual/_rollupPluginBabelHelpers.js"

    node_modules/.pnpm/@ensdomains+ens-avatar@0.3.2/node_modules/@ensdomains/ens-avatar/dist/index.esm.js:1:108:
      1 │ import { inheritsLoose as _inheritsLoose, asyncToGenerator as _asyncToGenerator, extends as _extends } from '../_virtual/_rollupPluginBabelHelpers.js';
        ╵                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/regenerator-runtime/runtime.esm.js"

    node_modules/.pnpm/@ensdomains+ens-avatar@0.3.2/node_modules/@ensdomains/ens-avatar/dist/index.esm.js:2:32:
      2 │ import _regeneratorRuntime from '../node_modules/regenerator-runtime/runtime.esm.js';
        ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

We are using PNPM & Vite and in versions 3+ we experience this issue. 

Downgrading to 0.2.5 is our current fix so this issue doesn't occur.

**Comment by mdtanrikulu** [comment]
Hey @nickdoherty, thanks for the report! I double-checked and it seems there was a bug in the pre-publish packing process. Made a fix and published the new version `0.3.3`. Please let me know if it solves your problem.

**Comment by nickdoherty** [comment]
Perfect, thank you so much! This has fixed the issue.

**Comment by fabriguespe** [comment]
This is still happening to me on Vercel

<img width="1018" alt="CleanShot 2023-09-26 at 16 18 17@2x" src="https://github.com/ensdomains/ens-avatar/assets/1447073/05694554-8662-4d74-b501-647675f54e09">

**Comment by nickdoherty** [comment]
I have the same issue as @fabriguespe when using Bun/docker for deployment. Strange enough it build locally, issue appears isolated to CI.

It works fine using Pnpm/npm using docker or building locally.

```
3.321  ERROR  Could not resolve "./node_modules/regenerator-runtime/runtime.esm.js" from "node_modules/@ensdomains/ens-avatar/dist/index.esm.js"
3.321 file: /app/node_modules/@ensdomains/ens-avatar/dist/index.esm.js
3.321
3.324
3.324  ERROR  error during build:
3.324 RollupError: Could not resolve "./node_modules/regenerator-runtime/runtime.esm.js" from "node_modules/@ensdomains/ens-avatar/dist/index.esm.js"
3.324     at error (/app/node_modules/rollup/dist/es/shared/parseAst.js:339:10)
3.324     at <anonymous> (/app/node_modules/rollup/dist/es/shared/node-entry.js:17894:9)
3.324     at processTicksAndRejections (:61:39)
```

**Comment by mdtanrikulu** [comment]
@nickdoherty @fabriguespe does this happen with v0.3.3 ?

**Comment by nickdoherty** [comment]
Still occurs on 0.3.3 for me. Currently using 0.3.5.

**Comment by fabriguespe** [comment]
Yes happens also with 0.3.5

**Comment by mdtanrikulu** [comment]
sorry for the long due. with version 0.3.6, this issue must disappear, please let me know if the issue still persist.
